# Generated by Django 4.2.23 on 2025-08-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietrackerdb',
            name='content_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], default='Movie', max_length=20),
        ),
        migrations.AddField(
            model_name='movietrackerdb',
            name='episodes_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movietrackerdb',
            name='platform',
            field=models.CharField(choices=[('netflix', 'Netflix'), ('prime', 'Prime')], default='prime', max_length=100),
        ),
        migrations.AddField(
            model_name='movietrackerdb',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movietrackerdb',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movietrackerdb',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], default='wishlist', max_length=20),
        ),
        migrations.AddField(
            model_name='movietrackerdb',
            name='total_episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movietrackerdb',
            name='director',
            field=models.CharField(default='dir 1', max_length=300),
        ),
        migrations.AlterField(
            model_name='movietrackerdb',
            name='title',
            field=models.CharField(default='test 1', max_length=300),
        ),
    ]
