# Generated by Django 4.2.23 on 2025-08-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_movietrackerdb_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietrackerdb',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='movietrackerdb',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='movietrackerdb',
            name='status',
        ),
    ]
