# Generated by Django 4.2.23 on 2025-08-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_remove_movietrackerdb_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietrackerdb',
            name='platform',
            field=models.CharField(choices=[('netflix', 'Netflix'), ('prime', 'Prime')], default='prime', max_length=100),
        ),
        migrations.AlterField(
            model_name='movietrackerdb',
            name='director',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movietrackerdb',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
