# Generated by Django 4.2.23 on 2025-08-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_movietrackerdb_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietrackerdb',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], default='wishlist', max_length=20),
        ),
    ]
