# Generated by Django 4.2.23 on 2025-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_movietrackerdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietrackerdb',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv Show', 'TV Show')], default='Movie', max_length=20),
        ),
    ]
