# Generated by Django 4.2.23 on 2025-08-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0006_movietrackerdb_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietrackerdb',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance'), ('comedy', 'Comedy'), ('fantasy', 'Fantasy'), ('action', 'Action')], default='Romance', max_length=100),
        ),
    ]
