# Generated by Django 4.2.23 on 2025-08-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0007_movietrackerdb_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietrackerdb',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv Show', 'TV Show')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movietrackerdb',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance'), ('comedy', 'Comedy'), ('fantasy', 'Fantasy'), ('action', 'Action')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movietrackerdb',
            name='platform',
            field=models.CharField(choices=[('netflix', 'Netflix'), ('prime', 'Prime')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movietrackerdb',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], max_length=20),
        ),
    ]
